name: realtime_quiz_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  bloc_concurrency: ^0.3.0

  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^8.0.0
  pin_code_fields: ^8.0.1
  rxdart: ^0.28.0
  supabase_flutter: ^2.12.0
  toastification: ^3.0.3
  uuid: ^4.5.2

dev_dependencies:
  bloc_lint: ^0.3.6
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
  go_router_builder: ^4.1.3
  json_serializable: ^6.12.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
